#!/bin/sh
die() {
	echo "$1" >&2
	exit 1
}

gen_csv(){
	sed "s/'/\'/;s/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g;s%"NULL"%%g" 
}

[ -r "$HOME/.my.cnf" ] || die "ERROR: ~/.my.cnf not found"

OUT_GRUPOS1="$HOME/eval2_grupos1.csv"
OUT_GRUPOS2="$HOME/eval2_grupos2.csv"
OUT_GRUPOS2_TMP="$(tempfile)"

#FSSERVER="-h 10.10.0.250"
PROCESSMAKER=""
SELECT_BASE1="SELECT APP_NUMBER, DATETIME_JEVAL"
SELECT_BASE2="DROP_EVALUACION, TEXT_TUTOR, RADIO_ASISTENCIA, RADIO_ACUERDOS, TXTA_VALORACIONES_REPRESENTANTES_GRUPO, TEXTA_VALORACIONES_GRUPO, TEXTA_CONSIDERACIONES_MODULO, TEXTA_CONSIDERACIONES_ALUMNO, TEXTA_CONSIDERACIONES_JE, TEXTAR_OBSERVACIONS"
SELECT_BASE3=""
n=1
while [ $n -le 12 ] ; do
	SELECT_BASE3="$SELECT_BASE3, TEXT_MODULO${n}, TEXT_PROFESOR${n}, CHECKBOX_ASISTENCIA${n}, CHECKBOX_DISCONFORMIDAD${n}, TEXT_MOTIVODISCONF${n}"
	n=$(($n +1))
done

#SELECT_FIN="FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' ESCAPED BY ‘\\’ LINES TERMINATED BY '\\n' "

SELECT_PRIMEROS="$SELECT_BASE1, DROP_FAMILIA, DROP_CURSO, DROP_GRUPO_CABECERA, $SELECT_BASE2 $SELECT_BASE3 FROM PMT_JEVAL_ACTA_1_revisada WHERE 1"
SELECT_SEGUNDOS="$SELECT_BASE1, TEXT_FAMILIA, TEXT_CURSO, DROP_GRUPO, $SELECT_BASE2 FROM PMT_JEVAL_ACTA_2_revisada WHERE 1"

mysql $PROCESSMAKER -B -e "use simple_itaca; $SELECT_PRIMEROS" | gen_csv > "$OUT_GRUPOS1"
mysql $PROCESSMAKER -B -e "use simple_itaca; $SELECT_SEGUNDOS" | gen_csv > "$OUT_GRUPOS2_TMP"


SELECT_FIRMAS_BASE="SELECT f.TEXTG_MODULO, CONCAT(p.apellido1, ' ', p.apellido2, ', ', p.nombre) as profesor, f.CHECKBOX_ASISTE, f.CHECKBOX_CONFORME, '' as motivo FROM PMT_JEVAL_FIRMAS_2 as f, profesores_pm as p  WHERE CONCAT(p.login, '@ausiasmarch.net') = f.DROP_PROFESOR"

FIRMAS_TMP="$(tempfile)"
# iterate over list of APP_NUMBER
head -1 "$OUT_GRUPOS1" > "$OUT_GRUPOS2"
cat "$OUT_GRUPOS2_TMP"  |while read line; do
	APP_NUMBER="$(echo "$line"|cut -f 2 -d \")"
	SELECT_FIRMAS2="$SELECT_FIRMAS_BASE AND f.APP_NUMBER = '$APP_NUMBER'"
#	echo $SELECT_FIRMAS2
	mysql $PROCESSMAKER -B -N -e "use simple_itaca; $SELECT_FIRMAS2" | gen_csv |tr "\n" "," > "$FIRMAS_TMP"
	if [ -s "$FIRMAS_TMP" ] ; then
		echo "${line},$(cat "$FIRMAS_TMP")" >> "$OUT_GRUPOS2"
	fi
done

echo "creados $OUT_GRUPOS1 y $OUT_GRUPOS2"
rm -f "$OUT_GRUPOS2_TMP" "$FIRMAS_TMP"
#mysql $PROCESSMAKER --local-infile=1 -N -B -e "use simple_itaca; truncate table grupos_pm; load xml local infile '$GROUP_XML' into table grupos_pm character set utf8;"


