#!/bin/sh
die() {
        echo "$1" >&2
        exit 1
}

# $1 => "original" llxgesc.xml (export from itaca to "aula LliureX")

# basic tests
[ "$1" ] || die "usage: $0 LLXGESC_FILE"

[ $(id -u) -eq 0 ] || die "You must be root to run this script"

# check configuration files
[ -r /root/.my.cnf ] || die "Missing mysql configurarion in /root/.my.cnf"
export HOME=/root

LLXGESC="$1"
[ -r "$LLXGESC" ] || die "ERROR: usage: $0 LLXGESC_FILE"

# 1. create new file with line feeds
LLXGESC_LINES="$(tempfile)"

sed -e "s%<\([^\/]\)%\n<\1%g" "$LLXGESC" > "$LLXGESC_LINES"

# extract "assignatures" to a new xml
ASSIGNATURES_XML="$(tempfile)"
sed -e "1,/<assignatures>/d;s%\(<\/assignatures>\)%\n\1%" "$LLXGESC_LINES" | sed -e "/<\/assignatures>/,\$d" > "$ASSIGNATURES_XML"

mysql --local-infile=1 -N -B -e "use itaca; truncate table assignatures; load xml local infile '$ASSIGNATURES_XML' into table assignatures character set utf8 rows identified by '<assignatura>';"

PROFES_XML="$(tempfile)"
GRUPOASI_XML="$(tempfile)"

sed -e "1,/<professors>/d;s%\(<\/professors>\)%\n\1%" "$LLXGESC_LINES" | sed -e "/<\/professors>/,\$d" > "$PROFES_XML"

# extraer dnis :
sed -ne "/<document>/{s%^.*<document>%%;s%<\/document>.*$%%;p}" "$PROFES_XML" |while read dni; do
# iterar por dni, parseando su bloque:
	sed -ne "/<document>${dni}/,/<\/professor>/{/<grupoassignatura>/{s%<grupoassignatura>%%;s%#% %;s%<\/grupoassignatura>.*$%%;p}}" "$PROFES_XML" |while read grupo cursoasignatura; do
		asignatura="$(echo "$cursoasignatura" |cut -c '5-')"
		cat >> "$GRUPOASI_XML" <<EOF
<row>
	<grupo>$grupo</grupo>
	<asignatura>$asignatura</asignatura>
	<profesor>$dni</profesor>
</row>
EOF
	done
done

mysql --local-infile=1 -N -B -e "use itaca; truncate table grupoasiprof; load xml local infile '$GRUPOASI_XML' into table grupoasiprof character set utf8;"

#cat "$GRUPOASI_XML" > grupoasi.xml

rm -f "$LLXGESC_LINES" "$ASSIGNATURES_XML" "$PROFES_XML" "$GRUPOASI_XML"

UPDATE_TUTOR="UPDATE profesores AS p, grupoasiprof AS g SET p.tutoria = g.grupo WHERE (g.profesor = p.dni AND g.asignatura like 'TU%')"
mysql --local-infile=1 -N -B -e "use itaca; $UPDATE_TUTOR;"
UPDATE_TUTOR2="UPDATE grupos AS g, grupoasiprof AS a SET g.tutor_ppal = a.profesor WHERE (a.grupo = g.codigo AND a.asignatura like 'TU%')"
mysql --local-infile=1 -N -B -e "use itaca; $UPDATE_TUTOR2;"

